[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'tyru/caw.vim.git'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# git
[[plugins]]
# git diff, log
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'


[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  au load_theme VimEnter * nested colorscheme hybrid
'''
# repo = 'chriskempson/vim-tomorrow-theme'
# hook_add = '''
#   au load_theme VimEnter * nested colorscheme Tomorrow-Night 
# '''

[[plugins]]
repo = 'itchyny/lightline.vim'

# highlight ts syntax
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['ts, tsx']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'iloginow/vim-stylus'
on_ft = 'styl'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
on_ft = ['html', 'css', 'styl', 'vue']


[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = 'let g:deoplete#enable_at_startup = 1'

# https://github.com/Shougo/deoplete.nvim/wiki/Completion-Sources

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['js', 'jsx', 'vue']
build = 'npm install -g tern'

# required by nvim-typescript
# [[plugins]]
# repo = 'HerringtonDarkholme/yats.vim'
# on_ft = ['ts', 'tsx', 'vue']

# [[plugins]]
# repo = 'mhartington/nvim-typescript'
# on_ft = ['ts', 'tsx']
# build = './install'

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = ['python']
on_i = 1
# hook_add = '''
#   let g:deoplete#sources#jedi#python_path = /path/to/python3
# '''
[[plugins]]
repo = 'tidalcycles/vim-tidal'
on_ft = ['tidal']
rev='tidal-0.9'

# cpp
[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = ['cpp']

# [[plugins]]
# repo = 'osyo-manga/vim-marching'
# on_ft = ['cpp']

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['cpp']
