# highlight javascrpit syntax
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js, jsx']

# highlight es6 syntax
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['js, jsx']

# highlight jsx syntax
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['js, jsx']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['jade, pug']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'scss', 'js']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = 'snippet'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'galooshi/vim-import-js'
on_ft = ['js, jsx']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'rb'

# checker
[[plugins]]
repo = 'w0rp/ale' 
on_ft = ['js', 'jsx']

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = 'Tagbar'
