[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'junegunn/fzf'
build = './install'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# git
[[plugins]]
# git diff, log
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.vim/rc/plugins/vim-fugitive.vim
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  colorscheme onedark
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
       \ 'colorscheme': 'onedark',
       \ 'active': {
       \   'right': [ [ 'lineinfo' ],
       \              [ 'percent' ],
       \              [ 'empty' ] ]
       \ },
       \ 'component_function': {
       \   'filename': 'LightlineFilename',
       \   'empty': 'Empty'
       \ }
       \ }
        " \   'paneinfo': 'PaneInfo',
        " \   'left':  [ ['paneinfo'] ],
  " function! PaneInfo()
  "   return %{winnr()}
  " endfunction
  "
  function! Empty()
    return ""
  endfunction

  function! LightlineFilename()
    return &filetype ==# 'vimfiler' ? vimfiler#get_status_string() :
         \ &filetype ==# 'unite' ? unite#get_status_string() :
         \ &filetype ==# 'vimshell' ? vimshell#get_status_string() :
         \ expand('%:p') !=# '' ? expand('%:p') : '[No Name]'
  endfunction
'''


[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']


[[plugins]]
repo = 'rizzatti/dash.vim'
hook_add = 'nmap <silent> <Leader><Leader>d <Plug>DashSearch'

[[plugins]]
repo = 'thinca/vim-quickrun'


[[plugins]] # display marks
repo='kshenoy/vim-signature'
hook_add = '''
  let g:SignatureMap = {
    \ 'GotoNextLineAlpha'  :  "",
    \ 'GotoPrevLineAlpha'  :  "",
    \ }
'''

[[plugins]]
repo = 'tpope/vim-commentary'
