[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# git
[[plugins]]
# git diff, log
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  augroup load-theme
    autocmd!
    autocmd load-theme VimEnter * nested colorscheme hybrid
  augroup END
'''
# repo = 'chriskempson/vim-tomorrow-theme'
# hook_add = '''
#   au load_theme VimEnter * nested colorscheme Tomorrow-Night 
# '''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# カーソル位置のコンテキストに合わせてftを切り替える
# [[plugins]]
# repo = 'osyo-manga/vim-precious'
# depends = ['context_filetype.vim']

# # # https://muunyblue.github.io/520bae6649b42ff5a3c8c58b7fcfc5a9.html
# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# # depends = ['deoplete.nvim']
# build = 'bash install.sh'
# # on_ft = ['vue', 'cpp']

# [[plugins]]
# repo = 'rizzatti/dash.vim'
# hook_add = 'nmap <silent> <Leader>d <Plug>DashSearch'

# lsp
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
build = 'npm install -g  typescript-language-server'
