
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js, jsx']

# highlight es6 syntax
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['js, jsx']

# highlight jsx syntax
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['js, jsx']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['jade, pug']
#
# [[plugins]]
# repo = 'kchmck/vim-coffee-script'
# on_ft = ['coffee']
#
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'scss', 'js']

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = ['InsertEnter']
on_ft = 'snippet'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'galooshi/vim-import-js'
on_ft = ['js, jsx']

# [[plugins]]
# repo = 'tpope/vim-endwise'
# on_ft = 'rb'

# checker
[[plugins]]
repo = 'w0rp/ale' 
on_ft = ['vue', 'ts', 'tsx', 'js', 'jsx', 'vim']

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = 'Tagbar'

# highlight ts syntax
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['ts', 'tsx', 'vue']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_add = '''
set iskeyword+=$
set iskeyword+=-
'''

[[plugins]]
repo = 'iloginow/vim-stylus'
on_ft = ['styl', 'vue']

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
on_ft = ['html', 'css', 'styl', 'vue']

[[plugins]]
repo = 'tidalcycles/vim-tidal'
on_ft = ['tidal']
rev='tidal-0.9'

# cpp
[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = ['cpp']

# [[plugins]]
# repo = 'osyo-manga/vim-marching'
# on_ft = ['cpp']

# vueのlsp serverがあまり補完が強くないので使用
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
do = 'UpdateRemotePlugins'
on_event = ['InsertEnter']
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
on_event = ['InsertEnter']
do = './install.sh'

[[plugins]]
repo = 'prabirshrestha/async.vim'
on_ft = ['ts', 'vue']

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_ft = ['ts', 'vue']

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_ft = ['ts', 'vue']
