# highlight es6 syntax
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'jsx']

# highlight jsx syntax
[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'jsx']
hook_add = '''
  let g:vim_jsx_pretty_highlight_close_tag = 1
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'scss', 'javascript']

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = ['InsertEnter']
on_ft = 'snippet'

[[plugins]]
repo = 'galooshi/vim-import-js'
on_ft = ['javascript', 'jsx']

# [[plugins]]
# repo = 'tpope/vim-endwise'
# on_ft = 'rb'

# checker
[[plugins]]
repo = 'w0rp/ale' 
on_ft = ['vue', 'typescript', 'tsx', 'js', 'jsx', 'vim']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_add = '''
  set iskeyword+=$
  set iskeyword+=-
'''

[[plugins]]
repo = 'iloginow/vim-stylus'
on_ft = ['styl', 'vue']

[[plugins]]
repo = 'tidalcycles/vim-tidal'
on_ft = ['tidal']
rev='tidal-0.9'

# [[plugins]]
# repo = 'osyo-manga/vim-marching'
# on_ft = ['cpp']

# vueのlsp serverがあまり補完が強くないので使用
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
do = ':UpdateRemotePlugins'
on_event = ['InsertEnter']
on_ft = ['javascript', 'vue']
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
on_ft = ['javascript', 'vue']
on_event = ['InsertEnter']
build = './install.sh'


[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_ft = ['typescript', 'vue']

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_ft = ['typescript', 'vue']
