[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'tyru/caw.vim.git'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'itchyny/lightline.vim'

# syntax highlight

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['jade, pug']

# highlight javascrpit syntax
[[plugins]]
repo = 'pangloss/vim-javascript'

# highlight es6 syntax
[[plugins]]
repo = 'othree/yajs.vim'

# highlight jsx syntax
[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'cespare/vim-toml'

# git
[[plugins]]
# git diff, log
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# checker
[[plugins]]
repo = 'w0rp/ale' 
