[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'tyru/caw.vim.git'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# git
[[plugins]]
# git diff, log
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'


[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  au load_theme VimEnter * nested colorscheme hybrid
'''
# repo = 'chriskempson/vim-tomorrow-theme'
# hook_add = '''
#   au load_theme VimEnter * nested colorscheme Tomorrow-Night 
# '''

[[plugins]]
repo = 'itchyny/lightline.vim'
