[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'VimEnter'
# repo = 'vim-denops/denops.vim'
# on_func = 'denops#server#start'
# hook_source = 'call denops#server#start()'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufEnter'
depends     = ['nvim-lsp-installer']
hook_source = 'luafile ~/.vim/rc/plugins/lua/nvim-lspconfig.lua'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
on_source = 'nvim-lspconfig'
hook_source = 'luafile ~/.vim/rc/plugins/lua/nvim-lsp-installer.lua'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'jsx', 'tsx']
hook_add = '''
  let g:vim_jsx_pretty_highlight_close_tag = 0
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'scss', 'javascript', 'vue', 'php', 'jsx', 'tsx']

[[plugins]]
repo = 'dense-analysis/ale' 
on_cmd = ['ALEFix', 'ALEFixSuggest', 'ALELint', 'ALEToggle', 'ALEEnable', 'ALEToggleBuffer', 'ALEEnableBuffer', 'ALENextWrap', 'ALEPreviousWrap']
# on_func = 'ale#completion#OmniFunc'
on_ft = ['typescript', 'vue', 'cpp']
hook_source = 'source ~/.vim/rc/plugins/ale.vim'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_add = '''
  set iskeyword+=$
  set iskeyword+=-
'''

[[plugins]]
repo = 'iloginow/vim-stylus'
on_ft = ['styl', 'vue']

# [[plugins]]
# repo = 'codota/tabnine-vim'
## on_ft = ['vue']

# [[plugins]]
# repo = 'pdavydov107/vim-lsp-cquery'
# on_ft = ['cpp']
# hook_add = '''
# 	autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fv :LspCqueryDerived<CR>
# 	autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fc :LspCqueryCallers<CR>
# 	autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fb :LspCqueryBase<CR>
# 	autocmd FileType c,cc,cpp,cxx,h,hpp nnoremap <leader>fi :LspCqueryVars<CR>
# '''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_ft = ['typescript', 'vue', 'cpp']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  let g:vim_markdown_folding_disabled = 0
  let g:vim_markdown_new_list_item_indent = -1
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ['InsertEnter']

[[plugins]]
repo='mattn/sonictemplate-vim'
on_event= ['CmdlineEnter']

[[plugins]]
repo = 'scrooloose/nerdcommenter'
on_ft = ['vue']
hook_source = 'source ~/.vim/rc/plugins/nerdcommenter.vim'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']

[[plugins]]
repo = "neoclide/coc.nvim"
rev = "release"
on_ft = ['dart']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
hook_add = '''
  let g:vim_jsx_pretty_highlight_close_tag = 0
'''
