[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'VimEnter'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'scss', 'javascript', 'vue', 'php', 'jsx', 'tsx', 'markdown']
hook_source = '''
  source ~/.vim/rc/plugins/emmet-vim.vim
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
  let g:vim_markdown_new_list_item_indent = -1
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ['InsertEnter']

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']
hook_add = '''
  nnoremap <leader>fa :FlutterRun<cr>
  nnoremap <leader>fq :FlutterQuit<cr>
  nnoremap <leader>fh :FlutterHotReload<cr>
  nnoremap <leader>fR :FlutterHotRestart<cr>
  nnoremap <leader>fD :FlutterVisualDebug<cr>
'''

[[plugins]]
repo = 'ferrine/md-img-paste.vim'
on_ft = ['markdown']
hook_add = '''
autocmd FileType markdown nmap <buffer><silent> <leader>p :call mdip#MarkdownClipboardImage()<CR>
" there are some defaults for image directory and image name, you can change them
let g:mdip_imgdir = 'img'
let g:mdip_imgname = 'image'
'''


[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']
