[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'tyru/caw.vim.git'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# git
[[plugins]]
# git diff, log
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'


[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  au load_theme VimEnter * nested colorscheme hybrid
'''
# repo = 'chriskempson/vim-tomorrow-theme'
# hook_add = '''
#   au load_theme VimEnter * nested colorscheme Tomorrow-Night 
# '''

[[plugins]]
repo = 'itchyny/lightline.vim'

# highlight ts syntax
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['ts, tsx']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'iloginow/vim-stylus'
on_ft = 'styl'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
on_ft = ['html', 'css', 'styl', 'vue']

[[plugins]]
repo = 'tidalcycles/vim-tidal'
on_ft = ['tidal']
rev='tidal-0.9'

# cpp
[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = ['cpp']

# [[plugins]]
# repo = 'osyo-manga/vim-marching'
# on_ft = ['cpp']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# vueのlsp serverがあまり補完が強くないので使用
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
do = 'UpdateRemotePlugins'
on_i = 1
on_ft = ['vue']
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
on_event = ['InsertEnter']
build = './install.sh'
on_ft = ['vue']

# # # https://muunyblue.github.io/520bae6649b42ff5a3c8c58b7fcfc5a9.html
# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# # depends = ['deoplete.nvim']
# build = 'bash install.sh'
# # on_ft = ['vue', 'cpp']

# [[plugins]]
# repo = 'rizzatti/dash.vim'
# hook_add = 'nmap <silent> <Leader>d <Plug>DashSearch'

# lsp
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
build = 'npm install -g  typescript-language-server'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

